FROM vault.habana.ai/gaudi-docker/1.17.0/ubuntu22.04/habanalabs/pytorch-installer-2.3.1:latest

ENV HABANA_VISIBLE_DEVICES=all
ENV OMPI_MCA_btl_vader_single_copy_mechanism=none
ENV PT_HPU_LAZY_ACC_PAR_MODE=0
ENV PT_HPU_ENABLE_LAZY_COLLECTIVES=1

# Install linux packages
ENV DEBIAN_FRONTEND="noninteractive"  TZ=Etc/UTC
RUN apt-get update && apt-get install -y tzdata bash-completion python3-pip openssh-server \
    vim git iputils-ping net-tools protobuf-compiler curl bc gawk tmux \
    && rm -rf /var/lib/apt/lists/*

# Add repo contents
ADD localGPT /root/localGPT
WORKDIR /root/localGPT

# Install python packages
RUN pip install --upgrade pip \
    && pip install langchain-experimental==0.0.62 \
    && pip install langchain==0.0.329 \
    && pip install protobuf==3.20.2 \
    && pip install grpcio-tools \
    && pip install pymilvus==2.4.0 \
    && pip install chromadb==0.5.15 \
    && pip install llama-cpp-python==0.1.66 \
    && pip install pdfminer.six==20221105 \
    && pip install transformers==4.43.1 \
    && pip install optimum[habana]==1.13.1 \
    && pip install InstructorEmbedding==1.0.1 \
    && pip install sentence-transformers==3.0.1 \
    && pip install faiss-cpu==1.7.4 \
    && pip install huggingface_hub==0.16.4 \
    && pip install protobuf==3.20.2 \
    && pip install auto-gptq==0.2.2 \
    && pip install docx2txt unstructured unstructured[pdf] urllib3 accelerate \
    && pip install bitsandbytes \
    && pip install click flask requests openpyxl \
    && pip install git+https://github.com/HabanaAI/DeepSpeed.git@1.17.0 \
    && pip install python-multipart \
    && pip install fastapi \
    && pip install uvicorn \
    && pip install gptcache==0.1.43 \
    && pip install pypdf==4.3.1 \
    && pip install python-jose[cryptography]
